name: UAT Deployement

on: 
  push: 
    branches:
      - master
      
jobs:
  
  deploy:
    runs-on: self-hosted
    name: deploy
    steps:
      - uses: action/checkout@v2
      - name: move code to live folder
        run: cp -f ./index.html /var/www/html/fox/index.html
